title: Fati Iseni - fiseni
description: >
  Fati Iseni 's blog on technology and software development.
permalink: ':title/'
baseurl:
url: "https://fiseni.com"
site-twitter:

author: Fati Iseni
author-img: fati-iseni.jpg
about-author: Software Architect | Developer
social-twitter: FatiIseni
social-github: fiseni
social-linkedin: fati-iseni-193928127
social-email: fati.iseni@pozitrongroup.com

# Disqus
discus-identifier: fiseni

# Tracker
analytics: G-6N7H7NRJZ7

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
